export const mockGroups = [
  {
    name: "A",
    standings: [
      {
        code: "mx",
        team_name: "México",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 2,
        goals_against: 0,
        goal_difference: 2,
        points: 3,
      },
      {
        code: "kr",
        team_name: "Corea del Sur",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 2,
        goals_against: 1,
        goal_difference: 1,
        points: 3,
      },
      {
        code: "cz",
        team_name: "República Checa",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 2,
        goal_difference: -1,
        points: 0,
      },
      {
        code: "za",
        team_name: "Sudáfrica",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 2,
        goal_difference: -2,
        points: 0,
      },
    ],
  },
  {
    name: "B",
    standings: [
      {
        code: "ca",
        team_name: "Canadá",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "ch",
        team_name: "Suiza",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "ba",
        team_name: "Bosnia-Herzegovina",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "qa",
        team_name: "Catar",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
    ],
  },
  {
    name: "C",
    standings: [
      {
        code: "br",
        team_name: "Brasil",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 1,
        goals_against: 1,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "ma",
        team_name: "Marruecos",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 1,
        goals_against: 1,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "gb-sct",
        team_name: "Escocia",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 1,
        goals_against: 0,
        goal_difference: 1,
        points: 3,
      },
      {
        code: "ht",
        team_name: "Haití",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 1,
        goal_difference: -1,
        points: 0,
      },
    ],
  },
  {
    name: "D",
    standings: [
      {
        code: "us",
        team_name: "Estados Unidos",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 4,
        goals_against: 1,
        goal_difference: 3,
        points: 3,
      },
      {
        code: "au",
        team_name: "Australia",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 2,
        goals_against: 0,
        goal_difference: 2,
        points: 3,
      },
      {
        code: "tr",
        team_name: "Turquía",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 2,
        goal_difference: -2,
        points: 0,
      },
      {
        code: "py",
        team_name: "Paraguay",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 4,
        goal_difference: -3,
        points: 0,
      },
    ],
  },
  {
    name: "E",
    standings: [
      {
        code: "de",
        team_name: "Alemania",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 7,
        goals_against: 1,
        goal_difference: 6,
        points: 3,
      },
      {
        code: "ci",
        team_name: "Costa de Marfil",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 1,
        goals_against: 0,
        goal_difference: 1,
        points: 3,
      },
      {
        code: "ec",
        team_name: "Ecuador",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 0,
        goals_against: 1,
        goal_difference: -1,
        points: 0,
      },
      {
        code: "cw",
        team_name: "Curazao",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 7,
        goal_difference: -6,
        points: 0,
      },
    ],
  },
  {
    name: "F",
    standings: [
      {
        code: "nl",
        team_name: "Países Bajos",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 2,
        goals_against: 2,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "jp",
        team_name: "Japón",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 2,
        goals_against: 2,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "se",
        team_name: "Suecia",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 5,
        goals_against: 1,
        goal_difference: 4,
        points: 3,
      },
      {
        code: "tn",
        team_name: "Túnez",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 5,
        goal_difference: -4,
        points: 0,
      },
    ],
  },
  {
    name: "G",
    standings: [
      {
        code: "be",
        team_name: "Bélgica",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 1,
        goals_against: 1,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "eg",
        team_name: "Egipto",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 1,
        goals_against: 1,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "ir",
        team_name: "Irán",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 2,
        goals_against: 2,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "nz",
        team_name: "Nueva Zelanda",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 2,
        goals_against: 2,
        goal_difference: 0,
        points: 1,
      },
    ],
  },
  {
    name: "H",
    standings: [
      {
        code: "es",
        team_name: "España",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "cv",
        team_name: "Cabo Verde",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "uy",
        team_name: "Uruguay",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 1,
        goals_against: 1,
        goal_difference: 0,
        points: 1,
      },
      {
        code: "sa",
        team_name: "Arabia Saudita",
        played: 1,
        wins: 0,
        draws: 1,
        losses: 0,
        goals_for: 1,
        goals_against: 1,
        goal_difference: 0,
        points: 1,
      },
    ],
  },
  {
    name: "I",
    standings: [
      {
        code: "fr",
        team_name: "Francia",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 3,
        goals_against: 1,
        goal_difference: 2,
        points: 3,
      },
      {
        code: "sn",
        team_name: "Senegal",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 3,
        goal_difference: -2,
        points: 0,
      },
      {
        code: "no",
        team_name: "Noruega",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 4,
        goals_against: 1,
        goal_difference: 3,
        points: 3,
      },
      {
        code: "iq",
        team_name: "Irak",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 4,
        goal_difference: -3,
        points: 0,
      },
    ],
  },
  {
    name: "J",
    standings: [
      {
        code: "ar",
        team_name: "Argentina",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "dz",
        team_name: "Argelia",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "at",
        team_name: "Austria",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "jo",
        team_name: "Jordania",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
    ],
  },
  {
    name: "K",
    standings: [
      {
        code: "pt",
        team_name: "Portugal",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "uz",
        team_name: "Uzbekistán",
        played: 1,
        wins: 0,
        draws: 0,
        losses: 1,
        goals_for: 1,
        goals_against: 3,
        goal_difference: -2,
        points: 0,
      },
      {
        code: "co",
        team_name: "Colombia",
        played: 1,
        wins: 1,
        draws: 0,
        losses: 0,
        goals_for: 3,
        goals_against: 1,
        goal_difference: 2,
        points: 3,
      },
      {
        code: "cd",
        team_name: "Congo RD",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
    ],
  },
  {
    name: "L",
    standings: [
      {
        code: "gb-eng",
        team_name: "Inglaterra",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "hr",
        team_name: "Croacia",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "gh",
        team_name: "Ghana",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
      {
        code: "pa",
        team_name: "Panamá",
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goals_for: 0,
        goals_against: 0,
        goal_difference: 0,
        points: 0,
      },
    ],
  },
];

export const mockMatches = [
  // Round 1 - June 11
  {
    id: 1,
    home_team: "México",
    away_team: "Sudáfrica",
    home_score: 2,
    away_score: 0,
    kickoff_utc: "2026-06-11T16:00:00Z",
    status: "complete",
    phase: "Grupo A",
    stadium: "Estadio Azteca",
    round: "Grupo A",
  },
  {
    id: 2,
    home_team: "Corea del Sur",
    away_team: "República Checa",
    home_score: 2,
    away_score: 1,
    kickoff_utc: "2026-06-11T19:00:00Z",
    status: "complete",
    phase: "Grupo A",
    stadium: "Estadio Guadalajara",
    round: "Grupo A",
  },

  // Round 1 - June 12
  {
    id: 3,
    home_team: "Canadá",
    away_team: "Suiza",
    home_score: 1,
    away_score: 1,
    kickoff_utc: "2026-06-12T17:00:00Z",
    status: "complete",
    phase: "Grupo B",
    stadium: "BC Place",
    round: "Grupo B",
  },
  {
    id: 26,
    home_team: "Bosnia-Herzegovina",
    away_team: "Catar",
    home_score: 1,
    away_score: 1,
    kickoff_utc: "2026-06-12T19:00:00Z",
    status: "complete",
    phase: "Grupo B",
    stadium: "BC Place",
    round: "Grupo B",
  },
  {
    id: 4,
    home_team: "Estados Unidos",
    away_team: "Paraguay",
    home_score: 4,
    away_score: 1,
    kickoff_utc: "2026-06-12T20:00:00Z",
    status: "complete",
    phase: "Grupo D",
    stadium: "SoFi Stadium",
    round: "Grupo D",
  },

  // Round 1 - June 13
  {
    id: 5,
    home_team: "Brasil",
    away_team: "Marruecos",
    home_score: 1,
    away_score: 1,
    kickoff_utc: "2026-06-13T15:00:00Z",
    status: "complete",
    phase: "Grupo C",
    stadium: "Gillette Stadium",
    round: "Grupo C",
  },
  {
    id: 6,
    home_team: "Escocia",
    away_team: "Haití",
    home_score: 1,
    away_score: 0,
    kickoff_utc: "2026-06-13T18:00:00Z",
    status: "complete",
    phase: "Grupo C",
    stadium: "MetLife Stadium",
    round: "Grupo C",
  },
  {
    id: 7,
    home_team: "Australia",
    away_team: "Turquía",
    home_score: 2,
    away_score: 0,
    kickoff_utc: "2026-06-13T21:00:00Z",
    status: "complete",
    phase: "Grupo D",
    stadium: "Lumen Field",
    round: "Grupo D",
  },

  // Round 1 - June 14
  {
    id: 8,
    home_team: "Alemania",
    away_team: "Curazao",
    home_score: 7,
    away_score: 1,
    kickoff_utc: "2026-06-14T15:00:00Z",
    status: "complete",
    phase: "Grupo E",
    stadium: "Levi's Stadium",
    round: "Grupo E",
  },
  {
    id: 9,
    home_team: "Países Bajos",
    away_team: "Japón",
    home_score: 2,
    away_score: 2,
    kickoff_utc: "2026-06-14T18:00:00Z",
    status: "complete",
    phase: "Grupo F",
    stadium: "Mercedes-Benz Stadium",
    round: "Grupo F",
  },
  {
    id: 10,
    home_team: "Costa de Marfil",
    away_team: "Ecuador",
    home_score: 1,
    away_score: 0,
    kickoff_utc: "2026-06-14T21:00:00Z",
    status: "complete",
    phase: "Grupo E",
    stadium: "Hard Rock Stadium",
    round: "Grupo E",
  },
  {
    id: 31,
    home_team: "Suecia",
    away_team: "Túnez",
    home_score: 5,
    away_score: 1,
    kickoff_utc: "2026-06-14T23:00:00Z",
    status: "complete",
    phase: "Grupo F",
    stadium: "Lumen Field",
    round: "Grupo F",
  },

  // Round 1 - June 15
  {
    id: 11,
    home_team: "España",
    away_team: "Cabo Verde",
    home_score: 0,
    away_score: 0,
    kickoff_utc: "2026-06-15T15:00:00Z",
    status: "complete",
    phase: "Grupo H",
    stadium: "Nrg Stadium",
    round: "Grupo H",
  },
  {
    id: 12,
    home_team: "Bélgica",
    away_team: "Egipto",
    home_score: 1,
    away_score: 1,
    kickoff_utc: "2026-06-15T18:00:00Z",
    status: "complete",
    phase: "Grupo G",
    stadium: "SoFi Stadium",
    round: "Grupo G",
  },
  {
    id: 13,
    home_team: "Arabia Saudita",
    away_team: "Uruguay",
    home_score: 1,
    away_score: 1,
    kickoff_utc: "2026-06-15T21:00:00Z",
    status: "complete",
    phase: "Grupo H",
    stadium: "Cotton Bowl",
    round: "Grupo H",
  },
  {
    id: 14,
    home_team: "Irán",
    away_team: "Nueva Zelanda",
    home_score: 2,
    away_score: 2,
    kickoff_utc: "2026-06-15T23:00:00Z",
    status: "complete",
    phase: "Grupo G",
    stadium: "Lincoln Financial Field",
    round: "Grupo G",
  },

  // Round 2 - June 15
  {
    id: 27,
    home_team: "México",
    away_team: "Corea del Sur",
    home_score: 1,
    away_score: 0,
    kickoff_utc: "2026-06-15T17:00:00Z",
    status: "complete",
    phase: "Grupo A",
    stadium: "Estadio Azteca",
    round: "Grupo A",
  },
  {
    id: 28,
    home_team: "República Checa",
    away_team: "Sudáfrica",
    home_score: 1,
    away_score: 1,
    kickoff_utc: "2026-06-15T19:00:00Z",
    status: "complete",
    phase: "Grupo A",
    stadium: "Estadio Guadalajara",
    round: "Grupo A",
  },

  // Round 1 - June 16
  {
    id: 15,
    home_team: "Francia",
    away_team: "Senegal",
    home_score: 3,
    away_score: 1,
    kickoff_utc: "2026-06-16T17:00:00Z",
    status: "complete",
    phase: "Grupo I",
    stadium: "BMO Field",
    round: "Grupo I",
  },
  {
    id: 16,
    home_team: "Irak",
    away_team: "Noruega",
    home_score: 1,
    away_score: 4,
    kickoff_utc: "2026-06-16T20:00:00Z",
    status: "complete",
    phase: "Grupo I",
    stadium: "Arrowhead Stadium",
    round: "Grupo I",
  },

  // Round 2 - June 16
  {
    id: 29,
    home_team: "Canadá",
    away_team: "Catar",
    home_score: 6,
    away_score: 0,
    kickoff_utc: "2026-06-16T19:00:00Z",
    status: "complete",
    phase: "Grupo B",
    stadium: "BC Place",
    round: "Grupo B",
  },
  {
    id: 30,
    home_team: "Suiza",
    away_team: "Bosnia-Herzegovina",
    home_score: 4,
    away_score: 1,
    kickoff_utc: "2026-06-16T21:00:00Z",
    status: "complete",
    phase: "Grupo B",
    stadium: "BC Place",
    round: "Grupo B",
  },

  // Round 1 - June 17
  {
    id: 32,
    home_team: "Argentina",
    away_team: "Argelia",
    home_score: 3,
    away_score: 0,
    kickoff_utc: "2026-06-17T17:00:00Z",
    status: "complete",
    phase: "Grupo J",
    stadium: "Estadio Azteca",
    round: "Grupo J",
  },
  {
    id: 33,
    home_team: "Austria",
    away_team: "Jordania",
    home_score: 3,
    away_score: 1,
    kickoff_utc: "2026-06-17T20:00:00Z",
    status: "complete",
    phase: "Grupo J",
    stadium: "SoFi Stadium",
    round: "Grupo J",
  },

  // Round 1 - June 18
  {
    id: 17,
    home_team: "Uzbekistán",
    away_team: "Colombia",
    home_score: 1,
    away_score: 3,
    kickoff_utc: "2026-06-18T20:00:00Z",
    status: "complete",
    phase: "Grupo K",
    stadium: "SoFi Stadium",
    round: "Grupo K",
  },
  {
    id: 34,
    home_team: "Portugal",
    away_team: "Congo RD",
    home_score: 1,
    away_score: 1,
    kickoff_utc: "2026-06-18T23:00:00Z",
    status: "complete",
    phase: "Grupo K",
    stadium: "Hard Rock Stadium",
    round: "Grupo K",
  },
  {
    id: 35,
    home_team: "Inglaterra",
    away_team: "Croacia",
    home_score: 4,
    away_score: 2,
    kickoff_utc: "2026-06-18T18:00:00Z",
    status: "complete",
    phase: "Grupo L",
    stadium: "MetLife Stadium",
    round: "Grupo L",
  },
  {
    id: 36,
    home_team: "Ghana",
    away_team: "Panamá",
    home_score: 1,
    away_score: 0,
    kickoff_utc: "2026-06-18T21:00:00Z",
    status: "complete",
    phase: "Grupo L",
    stadium: "Lumen Field",
    round: "Grupo L",
  },

  // Round 2 - June 19 (Today)
  {
    id: 18,
    home_team: "Estados Unidos",
    away_team: "Australia",
    home_score: 2,
    away_score: 0,
    kickoff_utc: "2026-06-19T19:00:00Z",
    status: "complete",
    phase: "Grupo D",
    stadium: "Lumen Field",
    round: "Grupo D",
  },
  {
    id: 19,
    home_team: "Brasil",
    away_team: "Haití",
    home_score: null,
    away_score: null,
    kickoff_utc: "2026-06-20T00:30:00Z",
    status: "scheduled",
    phase: "Grupo C",
    stadium: "AT&T Stadium",
    round: "Grupo C",
  },
  {
    id: 20,
    home_team: "Turquía",
    away_team: "Paraguay",
    home_score: null,
    away_score: null,
    kickoff_utc: "2026-06-20T03:00:00Z",
    status: "scheduled",
    phase: "Grupo D",
    stadium: "Gillette Stadium",
    round: "Grupo D",
  },
  {
    id: 21,
    home_team: "Escocia",
    away_team: "Marruecos",
    home_score: null,
    away_score: null,
    kickoff_utc: "2026-06-19T22:00:00Z",
    status: "scheduled",
    phase: "Grupo C",
    stadium: "Hard Rock Stadium",
    round: "Grupo C",
  },

  // Future matches
  {
    id: 22,
    home_team: "Alemania",
    away_team: "Ecuador",
    home_score: null,
    away_score: null,
    kickoff_utc: "2026-06-20T15:00:00Z",
    status: "scheduled",
    phase: "Grupo E",
    stadium: "Levi's Stadium",
    round: "Grupo E",
  },
  {
    id: 23,
    home_team: "Costa de Marfil",
    away_team: "Curazao",
    home_score: null,
    away_score: null,
    kickoff_utc: "2026-06-20T18:00:00Z",
    status: "scheduled",
    phase: "Grupo E",
    stadium: "Hard Rock Stadium",
    round: "Grupo E",
  },
  {
    id: 24,
    home_team: "Países Bajos",
    away_team: "Suecia",
    home_score: null,
    away_score: null,
    kickoff_utc: "2026-06-20T21:00:00Z",
    status: "scheduled",
    phase: "Grupo F",
    stadium: "Mercedes-Benz Stadium",
    round: "Grupo F",
  },
  {
    id: 25,
    home_team: "Japón",
    away_team: "Túnez",
    home_score: null,
    away_score: null,
    kickoff_utc: "2026-06-20T23:00:00Z",
    status: "scheduled",
    phase: "Grupo F",
    stadium: "Lumen Field",
    round: "Grupo F",
  },
];
