export const globalTeamCodes = {
  "Estados Unidos": "us",
  México: "mx",
  Canadá: "ca",
  Argentina: "ar",
  Brasil: "br",
  Francia: "fr",
  España: "es",
  Alemania: "de",
  "Congo RD": "cd",
  Italia: "it",
  Inglaterra: "gb-eng",
  Uruguay: "uy",
  Colombia: "co",
  "Corea del Sur": "kr",
  "República Checa": "cz",
  Sudáfrica: "za",
  "Bosnia-Herzegovina": "ba",
  "Irlanda del Norte": "ni",
  Marruecos: "ma",
  Escocia: "gb-sct",
  Haití: "ht",
  Australia: "au",
  Turquía: "tr",
  Paraguay: "py",
  "Costa de Marfil": "ci",
  Ecuador: "ec",
  Curazao: "cw",
  "Países Bajos": "nl",
  Japón: "jp",
  Suecia: "se",
  Túnez: "tn",
  Bélgica: "be",
  Egipto: "eg",
  Irán: "ir",
  "Nueva Zelanda": "nz",
  "Cabo Verde": "cv",
  "Arabia Saudita": "sa",
  Senegal: "sn",
  Noruega: "no",
  Irak: "iq",
  Argelia: "dz",
  Austria: "at",
  Jordania: "jo",
  Portugal: "pt",
  Uzbekistán: "uz",
  Honduras: "hn",
  Croacia: "hr",
  Ghana: "gh",
  Panamá: "pa",
  Catar: "qa",
  Suiza: "ch",
  Polonia: "pl",
  Perú: "pe",
  Ucrania: "ua",
  "Costa Rica": "cr",
  Hungría: "hu",
  Nigeria: "ng",
  Chile: "cl",
  "Saudi Arabia": "sa",
  Turkey: "tr",
};

export const flagUrl = (code) => (code ? `https://flagcdn.com/w40/${code.toLowerCase()}.png` : "");
