export const RATING_METADATA = {
  source: "Referencia FIFA + normalización interna",
  sourceUrl: "https://inside.fifa.com/fifa-world-ranking/men",
  updatedAt: "2026-06-11",
  methodology: "Semilla de fuerza informada por FIFA + forma local + modelo Poisson",
  disclaimer:
    "Las posiciones se normalizan internamente y no reproducen la tabla oficial completa de FIFA.",
};

// Semillas relativas para las 48 selecciones del dataset. Se usan únicamente
// como entrada del modelo predictivo y no deben mostrarse como ranking oficial.
export const teamStrengthSeeds = {
  Argentina: 1,
  España: 2,
  Francia: 3,
  Inglaterra: 4,
  Brasil: 5,
  Portugal: 6,
  "Países Bajos": 7,
  Bélgica: 8,
  Alemania: 9,
  Croacia: 10,
  Marruecos: 11,
  Italia: 12,
  Colombia: 13,
  Uruguay: 14,
  Japón: 15,
  "Estados Unidos": 16,
  México: 17,
  Suiza: 18,
  Senegal: 19,
  Irán: 20,
  Dinamarca: 21,
  Austria: 22,
  "Corea del Sur": 23,
  Australia: 24,
  Ecuador: 25,
  Turquía: 26,
  Suecia: 27,
  Noruega: 28,
  Canadá: 29,
  Egipto: 30,
  Argelia: 31,
  Panamá: 32,
  "Costa de Marfil": 33,
  Túnez: 34,
  Paraguay: 35,
  Escocia: 36,
  "República Checa": 37,
  "Arabia Saudita": 38,
  "Congo RD": 39,
  Sudáfrica: 40,
  Catar: 41,
  Uzbekistán: 42,
  Irak: 43,
  Ghana: 44,
  "Nueva Zelanda": 45,
  Jordania: 46,
  "Bosnia-Herzegovina": 47,
  "Cabo Verde": 48,
  Curazao: 49,
  Haití: 50,
};
