export const topScorers = [
  {
    name: "Kylian Mbappé",
    team: "Francia",
    teamCode: "fr",
    goals: 4,
    assists: 1,
    matches: 2,
    minutes: 166,
    photo: "/players/mbappe.webp",
  },
  {
    name: "Christian Pulisic",
    team: "Estados Unidos",
    teamCode: "us",
    goals: 3,
    assists: 1,
    matches: 2,
    minutes: 174,
    photo: "/players/pulisic.webp",
  },
  {
    name: "Harry Kane",
    team: "Inglaterra",
    teamCode: "gb-eng",
    goals: 3,
    assists: 0,
    matches: 2,
    minutes: 180,
    photo: "/players/kane.webp",
  },
  {
    name: "Lionel Messi",
    team: "Argentina",
    teamCode: "ar",
    goals: 2,
    assists: 2,
    matches: 2,
    minutes: 168,
    photo: "/players/messi.webp",
  },
];
